// <auto-generated />
using DDLootApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DDLootApp.Migrations
{
    [DbContext(typeof(LootContext))]
    [Migration("20190411173427_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DDLootApp.Models.Monster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("DDLootApp.Models.MonsterItems", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemDescription");

                    b.Property<string>("ItemName");

                    b.Property<int>("ItemPrice");

                    b.Property<int?>("ItemRarity");

                    b.Property<int>("MonsterID");

                    b.HasKey("ID");

                    b.HasIndex("MonsterID");

                    b.ToTable("MonsterItems");
                });

            modelBuilder.Entity("DDLootApp.Models.MonsterItems", b =>
                {
                    b.HasOne("DDLootApp.Models.Monster", "Monster")
                        .WithMany("MonsterItems")
                        .HasForeignKey("MonsterID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
